image: themattrix/tox

stages:
  - static_check
  - tests

before_script:
  - pip3.6 install -r requirements_dev.txt

static_check:
  stage: static_check
  script:
    - flake8 .

tests:
  stage: tests
  script:
  - tox
