image: themattrix/tox

stages:
  - static_check
  - tests

static_check:
  stage: static_check
  before_script:
    - pip3.6 install -r requirements_dev.txt
  script:
    - .tox/py36/bin/flake8 .

tests:
  stage: tests
  script:
  - tox
